# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

is_tbb <- function() {
    .Call(`_glow_is_tbb`)
}

c_map_glow <- function(x, y, intensity, radius, exponent, xdim, ydim, xmin, xmax, ymin, ymax, background, blend_mode, contrast_limit, nthreads) {
    .Call(`_glow_c_map_glow`, x, y, intensity, radius, exponent, xdim, ydim, xmin, xmax, ymin, ymax, background, blend_mode, contrast_limit, nthreads)
}

c_map_light <- function(x, y, intensity, radius, falloff_exponent, distance_exponent, xdim, ydim, xmin, xmax, ymin, ymax, background, blend_mode, nthreads) {
    .Call(`_glow_c_map_light`, x, y, intensity, radius, falloff_exponent, distance_exponent, xdim, ydim, xmin, xmax, ymin, ymax, background, blend_mode, nthreads)
}

mollweide_projection <- function(latitude, longitude, meridian) {
    .Call(`_glow_mollweide_projection`, latitude, longitude, meridian)
}

